name: flutter_app_futureback
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  firebase_analytics: ^8.1.0
  image_cropper: ^1.4.0
  cloud_firestore: ^2.2.0
  cached_network_image: ^3.0.0
  image_picker: ^0.7.5+3
  geolocator: ^7.0.3
  #geocoding: ^1.0.5
  auth: ^7.0.0
  camera: ^0.8.1+1
  uuid: 3.0.4
  path_provider: ^2.0.2
  firebase_storage: ^8.1.0
  timeago: ^3.0.2
  photo_view: ^0.11.1
  pinch_zoom: ^0.1.0
  firebase_messaging: ^10.0.0
  animated_bottom_navigation_bar: ^0.3.2
  flutter_local_notifications: ^6.0.0
  flutter_cache_manager: ^3.1.0
  progress_state_button: ^1.0.3
  google_sign_in: ^5.0.4
  cupertino_icons: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
  assets:
   - assets/images/google_signin_button1.png
   - assets/images/scard.png
   - assets/images/sccard.png
   - assets/images/logo.png
   - assets/images/logo2.png
   - assets/images/sscard.png
   - assets/images/manzara.jpg


