name: flutter_app_futureback
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.3.0
  firebase_auth: ^1.4.1
  firebase_analytics: ^8.1.2
  image_cropper: ^1.4.1
  cloud_firestore: ^2.2.2
  image_picker: ^0.8.0+3
  geolocator: ^7.1.0
  #geocoding: ^1.0.5
  camera: ^0.8.1+3
  uuid: ^3.0.4
  path_provider: ^2.0.2
  firebase_storage: ^8.1.3
  timeago: ^3.1.0
  photo_view: ^0.11.1
  pinch_zoom: ^0.1.0
  firebase_messaging: ^10.0.2
  animated_bottom_navigation_bar: ^0.3.2
  flutter_local_notifications: ^6.0.0
  progress_state_button: ^1.0.3
  google_sign_in: ^5.0.4
  #auth: ^8.0.0-pre+02
  image: ^3.0.2
  cupertino_icons: ^1.0.3
  shared_preferences: ^2.0.6
  cached_network_image: ^3.0.0
  fluttertoast: ^8.0.7
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
  assets:
   - assets/images/google_signin_button1.png
   - assets/images/scard.png
   - assets/images/sccard.png
   - assets/images/logo.png
   - assets/images/logo2.png
   - assets/images/sscard.png
   - assets/images/manzara.jpg


